image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      make
    command: |
      make help
vscode:
  extensions:
    - llvm-vs-code-extensions.vscode-clangd
    - twxs.cmake
    - cheshirekow.cmake-format
    - formulahendry.code-runner

